package de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox;

import de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.SensorValue;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Relation;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;
import io.objectbox.relation.ToOne;

/**
 * Created by Dennis on 25.08.2017.
 */
@Entity
public class StringEntity{
    @Id
    private long id;
    private String value;

    private int sortIndex;

    @Relation
    private SensorValue sensor_value;
    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;
    @Internal
    @Generated(1470185241)
    transient ToOne<SensorValue> sensor_valueToOne = new ToOne<>(this,
            StringEntity_.sensor_value);

    //Constructor
    public StringEntity(String value){
        this.value = value;
    }

    @Generated(1682256913)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public StringEntity(long id, String value, int sortIndex, long sensor_valueId) {
        this.id = id;
        this.value = value;
        this.sortIndex = sortIndex;
        this.sensor_valueToOne.setTargetId(sensor_valueId);
    }

    public int getSortIndex() {
        return sortIndex;
    }

    public void setSortIndex(int sortIndex) {
        this.sortIndex = sortIndex;
    }

    @Generated(773288025)
    public StringEntity() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
    /** To-one relationship, resolved on first access. */
    @Generated(150948073)
    public SensorValue getSensor_value() {
        sensor_value = sensor_valueToOne.getTarget();
        return sensor_value;
    }

    /** Set the to-one relation including its ID property. */
    @Generated(160285928)
    public void setSensor_value(SensorValue sensor_value) {
        sensor_valueToOne.setTarget(sensor_value);
        this.sensor_value = sensor_value;
    }
}
